### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by nikartz** [ssut/py-googletrans#106]
I get this Exception, no matter what I try. For testing porpuses I made a test.py with just the example given [here](https://github.com/ssut/py-googletrans#basic-usage):
```
from googletrans import Translator
translator = Translator()
translator.translate('안녕하세요.')
```
This is what I get (Windows and Debian):
```
python test.py
Traceback (most recent call last):
File "test.py", line 3, in <module>
translator.translate('안녕하세요.')
File "C:\Users\_____\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\client.py", line 172, in translate
data = self._translate(text, dest, src)
File "C:\Users\_____\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\client.py", line 81, in _translate
data = utils.format_json(r.text)
File "C:\Users\_____\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\utils.py", line 62, in format_json 
converted = legacy_format_json(original)
File "C:\Users\_____\AppData
File "C:\Users\_____\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
return _default_decoder.decode(s)
File "C:\Users\_____\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Users\_____\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
data = utils.format_json(r.text)
File "C:\Users\_____\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\utils.py", line 62, in format_json
converted = legacy_format_json(original)
File "C:\Users\_____\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\utils.py", line 54, in legacy_format_json
converted = json.loads(text)
File "C:\Users\_____\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
return _default_decoder.decode(s)
File "C:\Users\_____\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Users\_____\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Does anyone know, what to do?
I don't know, if this is also linked to [this](https://github.com/ssut/py-googletrans/issues/105), because there is Response 503 or any message from Google. 
My configuration has already worked. However, now it does not.

**Comment by MiroljubA** [comment]
Yes, it's the same thing as https://github.com/ssut/py-googletrans/issues/105. I just didn't post the python exception but extracted the google 503 message.
Tried on 2 different `ip`s, no luck :(

**Comment by Deepraj500** [comment]
See if you are pushing bulk requests. I got this error too, so I made the script print the response load. This is what the API had to say.


```
<Response [503]>
.
.
<br>Our systems have detected unusual traffic from your computer network.  This page checks to see if it&#39;s really you sending the requests, and not a robot.  <a href="#" onclick="document.getElementById('infoDiv').style.display='block';">Why did this happen?</a><br><br>
<div id="infoDiv" style="display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;">
This page appears when Google automatically detects requests coming from your computer network which appear to be in violation of the <a href="//www.google.com/policies/terms/">Terms of Service</a>. The block will expire shortly after those requests stop.  In the meantime, solving the above CAPTCHA will let you continue to use our services.<br><br>This traffic may have been sent by malicious software, a browser plug-in, or a script that sends automated requests.  If you share your network connection, ask your administrator for help &mdash; a different computer using the same IP address may be responsible.  <a href="//support.google.com/websearch/answer/86640">Learn more</a><br><br>Sometimes you may be asked to solve the CAPTCHA if you are using advanced terms that robots are known to use, or sending requests very quickly.
</div>
```

**Comment by Deepraj500** [comment]
oh, I poked into the client.py code in the package. The _translate method handles URL requests. I made the method print the response load.

**Comment by gitvivekgupta** [comment]
@Deepraj500 what do you mean by print response load?

        def _translate(self, text, dest, src):
        if not PY3 and isinstance(text, str):  # pragma: nocover
            text = text.decode('utf-8')

        token = self.token_acquirer.do(text)
        params = utils.build_params(query=text, src=src, dest=dest,
                                    token=token)
        url = urls.TRANSLATE.format(host=self._pick_service_url())
        r = self.session.get(url, params=params)

        data = utils.format_json(r.text)
        return data

**Comment by Deepraj500** [comment]
The session.get() sends a get ([doc](http://docs.python-requests.org/en/master/api/#requests.get)) request to the translate API carrying the params load and returns the response of the get request(in our case it is stored in 'r') which is a requests.Response class ([doc](http://docs.python-requests.org/en/master/api/#requests.Response)) object.

Try to look at what r has by printing the text class variable (in our case r.text). It will give you the content of the response, in Unicode.

**Comment by gitvivekgupta** [comment]
yes. but How to resolve the traffic error?

**Comment by Opdoop** [comment]
@MiroljubA How to using different IP?  
```python
translator = Translator(service_urls=translate_urls, proxies=proxy)
```
proxies didn't work for me.

**Comment by s4magier** [comment]
Same issue
