### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by gitvivekgupta** [ssut/py-googletrans#108]
I wrote this...

    translator = Translator()
    trans_token = translator.translate(token, dest='en', src='hi')
    new_token = trans_token.text

And I am getting this below error now.

When I ran at first it worked but stopped after sometime.
Now, It is not even going for one.

Please help ASAP

    Traceback (most recent call last):
      File "score.py", line 168, in <module>
        trans_token = translator.translate(token, dest='en', src='hi')
      File "/usr/local/lib/python3.7/site-packages/googletrans/client.py", line 172, in translate
        data = self._translate(text, dest, src)
      File "/usr/local/lib/python3.7/site-packages/googletrans/client.py", line 81, in _translate
        data = utils.format_json(r.text)
      File "/usr/local/lib/python3.7/site-packages/googletrans/utils.py", line 62, in format_json
        converted = legacy_format_json(original)
      File "/usr/local/lib/python3.7/site-packages/googletrans/utils.py", line 54, in legacy_format_json
        converted = json.loads(text)
      File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
        return _default_decoder.decode(s)
      File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Problem

    This page appears when Google automatically detects requests coming from your computer network which appear to be in violation of the <a href="//www.google.com/policies/terms/">Terms of Service</a>. The block will expire shortly after those requests stop.<br><br>This traffic may have been sent by malicious software, a browser plug-in, or a script that sends automated requests.  If you share your network connection, ask your administrator for help &mdash; a different computer using the same IP address may be responsible.  <a href="//support.google.com/websearch/answer/86640">Learn more</a><br><br>Sometimes you may see this page if you are using advanced terms that robots are known to use, or sending requests very quickly.
</div><br>

**Comment by prigioni** [comment]
I have got the error like you, but I don't know how to solve it.

**Comment by s4magier** [comment]
same error

**Comment by bourliam** [comment]
I have the same issue... Any idea ?? Thanks

**Comment by Devansh0112** [comment]
Just connect to your hotspot or restart your modem or use a vpn.... there is a limit per IP.
That should work. (Y)
