### ISSUE TITLE
Can't install---"UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 2476: illegal multibyte sequence"

### ISSUE THREAD

**Issue by al123xiaaaa** [ssut/py-googletrans#11]

**Comment by al123xiaaaa** [comment]
C:\WINDOWS\system32>pip install googletrans
Collecting googletrans
  Using cached googletrans-2.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\al123\AppData\Local\Temp\pip-build-l3vp7n93\googletrans\setup.py", line 56, in <module>
        install()
      File "C:\Users\al123\AppData\Local\Temp\pip-build-l3vp7n93\googletrans\setup.py", line 21, in install
        long_description=readme(),
      File "C:\Users\al123\AppData\Local\Temp\pip-build-l3vp7n93\googletrans\setup.py", line 11, in readme
        return f.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 2476: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\al123\AppData\Local\Temp\pip-build-l3vp7n93\googletrans\

**Comment by ssut** [comment]
What does `pip --version` give you?

**Comment by al123xiaaaa** [comment]
C:\WINDOWS\system32>pip --version
pip 9.0.1 from c:\users\al123\appdata\local\programs\python\python36\lib\site-packages (python 3.6)

I'm using windows10 chinese language.Is the GBK system encode problem?
