### ISSUE TITLE
Google automatically detects requests coming from your computer network which appear to be in violation of the Terms of Service. 

### ISSUE THREAD

**Issue by ishgupta** [ssut/py-googletrans#117]
Hello,

I keep on receiving the below error, with root cause being: "This page appears when Google automatically detects requests coming from your computer network which appear to be in violation of the Terms of Service. The block will expire shortly after those requests stop.<br><br>This traffic may have been sent by malicious software, a browser plug-in, or a script that sends automated requests.  If you share your network connection, ask your administrator for help &mdash; a different computer using the same IP address may be responsible.  <a href="//support.google.com/websearch/answer/86640">Learn more</a><br><br>Sometimes you may see this page if you are using advanced terms that robots are known to use, or sending requests very quickly."

Can anyone assist in resolving this?

I am working on Windows platform, in a workplace network. I also have access to network proxy if needed.

Traceback (most recent call last):
  Python Shell, prompt 3, line 1
    # Used internally for debug sandbox under external interpreter
  File "C:\Users\ish.gupta\AppData\Local\Programs\Python\Python37\Lib\site-packages\googletrans\client.py", line 174, in translate
    data = self._translate(text, dest, src)
  File "C:\Users\ish.gupta\AppData\Local\Programs\Python\Python37\Lib\site-packages\googletrans\client.py", line 83, in _translate
    data = utils.format_json(r.text)
  File "C:\Users\ish.gupta\AppData\Local\Programs\Python\Python37\Lib\site-packages\googletrans\utils.py", line 61, in format_json
    converted = legacy_format_json(original)
  File "C:\Users\ish.gupta\AppData\Local\Programs\Python\Python37\Lib\site-packages\googletrans\utils.py", line 53, in legacy_format_json
    converted = json.loads(text)
  File "C:\Users\ish.gupta\AppData\Local\Programs\Python\Python37\Lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ish.gupta\AppData\Local\Programs\Python\Python37\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ish.gupta\AppData\Local\Programs\Python\Python37\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Thanks,
Ish Gupta

**Comment by loicquirion** [comment]
Getting the same error here! I got two of my Ip Address blocked by Google Translate API!

**Comment by ryan-bin** [comment]
+1

**Comment by ronaldluc** [comment]
I usually got this after doing more than 400‒800 requests at once. It disappeared in 24 hours.
