### ISSUE TITLE
Python translator.translate source or 'src' error

### ISSUE THREAD

**Issue by gerimo** [ssut/py-googletrans#148]
Any source_langue

translation = translator.translate(text, src='es', dest='pt')

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/app/universal/test.py", line 35, in language_translation_tests
    return text_translator(source_language_code, translation_language_code, text)
  File "/app/app/language_translation/functions.py", line 8, in text_translator
    translation = translator.translate(text, src=source_language_code, dest=translation_language_code)
  File "/usr/local/lib/python3.7/site-packages/googletrans/client.py", line 146, in translate
    src = src.lower().split('_', 1)[0]
AttributeError: 'Detected' object has no attribute 'lower'

**Comment by Rickecr** [comment]
I was unable to reproduce the error. When trying to perform the translation as you described in the issue it worked normally.

Code:

```python3
from googletrans import Translator
text = "Hola mi nombre es rick"

translator = Translator()
translation = translator.translate(text, src='es', dest='pt')
print(translation.text) # 'Olá meu nome é rick'

````

Perhaps the issue has already been resolved and it may not have been checked here.
