### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by NexInfinite** [ssut/py-googletrans#171]
Everything was fine until i got this error. What does it mean and how can i fix this?

**Comment by Tobishua** [comment]
I recieve the same error

Traceback:
`Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "language.py", line 36, in do_POST
    result = translator.detect(text)
  File "/usr/local/lib/python3.5/dist-packages/googletrans/client.py", line 249, in detect
    data = self._translate(text, dest='en', src='auto')
  File "/usr/local/lib/python3.5/dist-packages/googletrans/client.py", line 81, in _translate
    data = utils.format_json(r.text)
  File "/usr/local/lib/python3.5/dist-packages/googletrans/utils.py", line 62, in format_json
    converted = legacy_format_json(original)
  File "/usr/local/lib/python3.5/dist-packages/googletrans/utils.py", line 54, in legacy_format_json
    converted = json.loads(text)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by Andrej730** [comment]
What version of googletrans do you have installed?
If it's latest from pypi then try the solution from #166 - change client parameter in request from 't' to either 'gtx' or 'webapp' in https://github.com/ssut/py-googletrans/blob/master/googletrans/utils.py file.

**Comment by NexInfinite** [comment]
> What version of googletrans do you have installed?
> If it's latest from pypi then try the solution from #166 - change client parameter in request from 't' to either 'gtx' or 'webapp' in https://github.com/ssut/py-googletrans/blob/master/googletrans/utils.py file.

Ill try this, give me like an hour

**Comment by NexInfinite** [comment]
Didnt work, but maybe its becuase my ip has been banned and i gotta wait

**Comment by imlegend19** [comment]
Getting the same error on running:

`translator.translate('Đào Huy Tuấn')`

**Comment by chuangzhanji** [comment]
> 
> 
> What version of googletrans do you have installed?
> If it's latest from pypi then try the solution from #166 - change client parameter in request from 't' to either 'gtx' or 'webapp' in https://github.com/ssut/py-googletrans/blob/master/googletrans/utils.py file.

'gtx' work fine
