### ISSUE TITLE
Library stopped working

### ISSUE THREAD

**Issue by KursX** [ssut/py-googletrans#193]
translate -c "안녕하세요."

```
Traceback (most recent call last):
  File "/usr/local/bin/translate", line 5, in <module>
    from googletrans import Translator
  File "/usr/local/lib/python3.5/dist-packages/googletrans/__init__.py", line 6, in <module>
    from googletrans.client import Translator
  File "/usr/local/lib/python3.5/dist-packages/googletrans/client.py", line 10, in <module>
    import httpcore
  File "/usr/local/lib/python3.5/dist-packages/httpcore/__init__.py", line 1, in <module>
    from ._async.base import AsyncByteStream, AsyncHTTPTransport
  File "/usr/local/lib/python3.5/dist-packages/httpcore/_async/base.py", line 9
    yield b""
       ^
```
SyntaxError: 'yield' inside async function

Or this trace

```
  File "/home/googletranslator.py", line 11, in start
    translation = translator.translate(text, src=src, dest=dest)
  File "/usr/local/lib/python3.5/dist-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/usr/local/lib/python3.5/dist-packages/googletrans/client.py", line 81, in _translate
    data = utils.format_json(r.text)
  File "/usr/local/lib/python3.5/dist-packages/googletrans/utils.py", line 62, in format_json
    converted = legacy_format_json(original)
  File "/usr/local/lib/python3.5/dist-packages/googletrans/utils.py", line 54, in legacy_format_json
    converted = json.loads(text)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
```

**Comment by KursX** [comment]
Even after installing on clean server

sudo apt-get install -y python3 python3-pip
sudo pip3 install googletrans
translate -c "안녕하세요."

**Comment by terryyz** [comment]
Hi, I just tried on my Linux VM. It seems okay to me. `translate -c` does work. Could you confirm that you made the other settings correct?

**Comment by KursX** [comment]
I did it on two different servers Ubuntu-16.04-x86_64
How can I check other settings? 

sudo pip3 uninstall googletrans
sudo pip3 install googletrans

Also not work

**Comment by KursX** [comment]
I launched clean server. Installed only pip3 and googletrans. And got the same error
You can check it yourself
ssh root@37.230.114.205
s27z9bSeH3On
May be problem with locales?

**Comment by terryyz** [comment]
Oops, didn't realize you were actually using Python3.5... Current googletrans is compatible with Python 3.6+ as you may check the README or pypi website for googletrans. Mine is python 3.6.2, so it works fine. Just use any version above 3.6 and try again.

**Comment by KursX** [comment]
Why did it work before? Minimum version increased?

**Comment by terryyz** [comment]
Yes, the min version requirement has recently been updated. In fact, Python 3.5 in list was just moved last month.

**Comment by KursX** [comment]
Can you add some python version checking to library? I have use this library for some years and it was very bad surprise for me and for my users. Thanks for this great tool

**Comment by terryyz** [comment]
Reasonable, will add version checking.
