### ISSUE TITLE
it's not working anymore 

### ISSUE THREAD

**Issue by jeiry** [ssut/py-googletrans#252]
no responds
no error
output nothing
just not working anymore....
the newest version.
yestoday was fine. I don't know why.

**Comment by jeiry** [comment]
I tried  translate -c hello


Traceback (most recent call last):
  File "/usr/local/bin/translate", line 40, in <module>
    main()
  File "/usr/local/bin/translate", line 21, in main
    result = translator.detect(args.text)
  File "/usr/local/lib/python3.7/dist-packages/googletrans/client.py", line 255, in detect
    data = self._translate(text, 'en', 'auto', kwargs)
  File "/usr/local/lib/python3.7/dist-packages/googletrans/client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "/usr/local/lib/python3.7/dist-packages/googletrans/gtoken.py", line 194, in do
    self._update()
  File "/usr/local/lib/python3.7/dist-packages/googletrans/gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by jeiry** [comment]
sorry i asked the same issue. check here https://github.com/ssut/py-googletrans/issues/234.
