### ISSUE TITLE
Version  googletrans==4.0.0-rc1  ERROR -> httpcore._exceptions.ConnectTimeout: _ssl.c:1106: The handshake operation timed out

### ISSUE THREAD

**Issue by gelodefaultbrain** [ssut/py-googletrans#261]
Hello! I tried this googletrans version `pip install googletrans==4.0.0-rc1` and I am translating a lot of data. Let's say there are bunch of sentences that I am translating inside of a python list now it works like for example for the first 10 sentences but then after is I get this error

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "F:\Desktop\Online Jobs files\Proj\TOOL BACKLOG A\TLA2 - Numbered List, Editing Items & Recent File\src\tmx.py", line 83, in process_table_data
    self.sorted_data = self.__process_word_data(word,lang_code,tmx_filepath)
  File "F:\Desktop\Online Jobs files\Proj\TOOL BACKLOG A\TLA2 - Numbered List, Editing Items & Recent File\src\tmx.py", line 196, in __process_word_data
    google_translation = self.translator.translate(sentence_result,src=lang_code,dest="en").text
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\googletrans\client.py", line 194, in translate
    data, response = self._translate(text, dest, src)
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\googletrans\client.py", line 120, in _translate
    r = self.client.post(url, params=params, data=data)
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpx\_client.py", line 824, in post
    return self.request(
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpx\_client.py", line 600, in request
    return self.send(
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpx\_client.py", line 620, in send
    response = self.send_handling_redirects(
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpx\_client.py", line 647, in send_handling_redirects
    response = self.send_handling_auth(
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpx\_client.py", line 684, in send_handling_auth
    response = self.send_single_request(request, timeout)
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpx\_client.py", line 714, in send_single_request
    ) = transport.request(
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpcore\_sync\connection_pool.py", line 152, in request
    response = connection.request(
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpcore\_sync\connection.py", line 65, in request
    self.socket = self._open_socket(timeout)
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpcore\_sync\connection.py", line 85, in _open_socket
    return self.backend.open_tcp_stream(
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpcore\_backends\sync.py", line 139, in open_tcp_stream
    return SyncSocketStream(sock=sock)
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore._exceptions.ConnectTimeout: _ssl.c:1106: The handshake operation timed out
```

I think it has something to do with me doing a request too fast? or more often? I will try to do a `time.sleep(sec)` to see if it could trick the conflict but I am posting this if ever there might be a solution. Thank you!

**Comment by gelodefaultbrain** [comment]
Now I tried putting a delay It went well for a few seconds but got this error tho...


```
   google_translation = self.translator.translate(sentence_result,src=lang_code,dest="en").text
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\googletrans\client.py", line 194, in translate
    data, response = self._translate(text, dest, src)
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\googletrans\client.py", line 120, in _translate
    r = self.client.post(url, params=params, data=data)
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpx\_client.py", line 824, in post
    return self.request(
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpx\_client.py", line 600, in request
    return self.send(
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpx\_client.py", line 620, in send
    response = self.send_handling_redirects(
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpx\_client.py", line 647, in send_handling_redirects
    response = self.send_handling_auth(
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpx\_client.py", line 684, in send_handling_auth
    response = self.send_single_request(request, timeout)
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpx\_client.py", line 714, in send_single_request
    ) = transport.request(
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpcore\_sync\connection_pool.py", line 152, in request
    response = connection.request(
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpcore\_sync\connection.py", line 65, in request
    self.socket = self._open_socket(timeout)
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpcore\_sync\connection.py", line 85, in _open_socket
    return self.backend.open_tcp_stream(
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpcore\_backends\sync.py", line 139, in open_tcp_stream
    return SyncSocketStream(sock=sock)
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore._exceptions.ConnectError: [WinError 10051] A socket operation was attempted to an unreachable network
```

**Comment by itsAPK** [comment]
Check your connection. May your VPN or proxy blocking the network

**Comment by gelodefaultbrain** [comment]
Hmmmm I am not using a VPN tho.. but let me check on the proxy. Thanks!

**Comment by forence** [comment]
> Hmmmm I am not using a VPN tho.. but let me check on the proxy. Thanks!

I meet the same problem, have you solve it now?

**Comment by gelodefaultbrain** [comment]
@forence  Hello! I think this happens when you make too many requests or translate a lot of data... did you happen to translate a lot of data? cause I was like probably 200+ I just kept repeating it & eventually it worked I got to translate the 200+ data. Also I think internet connection is a plus. But I'm still open for suggestion with the developers or other people

**Comment by forence** [comment]
@gelodefaultbrain Yes, the upper limit of requests is about 2000 times, and I deal with it by a 60s delay function. The effect is not bad, it has been running continuously for one day.

**Comment by thenewera-ru** [comment]
Does anyone has recent updates on the optimal `queries` per `ip` such that the address is not banned by Google?

**Comment by debjyoti003** [comment]
What I noticed is this happens at a particular time of the day, and it stays like this for a period of time, other than that specific time period it again gives output. I don't know why is it like that.

**Comment by eslamtalaat74** [comment]
> Hello! I tried this googletrans version `pip install googletrans==4.0.0-rc1` and I am translating a lot of data. Let's say there are bunch of sentences that I am translating inside of a python list now it works like for example for the first 10 sentences but then after is I get this error
> 
> ```
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "C:\Users\LENOVO\.conda\envs\USA24\lib\threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "C:\Users\LENOVO\.conda\envs\USA24\lib\threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "F:\Desktop\Online Jobs files\Proj\TOOL BACKLOG A\TLA2 - Numbered List, Editing Items & Recent File\src\tmx.py", line 83, in process_table_data
>     self.sorted_data = self.__process_word_data(word,lang_code,tmx_filepath)
>   File "F:\Desktop\Online Jobs files\Proj\TOOL BACKLOG A\TLA2 - Numbered List, Editing Items & Recent File\src\tmx.py", line 196, in __process_word_data
>     google_translation = self.translator.translate(sentence_result,src=lang_code,dest="en").text
>   File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\googletrans\client.py", line 194, in translate
>     data, response = self._translate(text, dest, src)
>   File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\googletrans\client.py", line 120, in _translate
>     r = self.client.post(url, params=params, data=data)
>   File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpx\_client.py", line 824, in post
>     return self.request(
>   File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpx\_client.py", line 600, in request
>     return self.send(
>   File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpx\_client.py", line 620, in send
>     response = self.send_handling_redirects(
>   File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpx\_client.py", line 647, in send_handling_redirects
>     response = self.send_handling_auth(
>   File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpx\_client.py", line 684, in send_handling_auth
>     response = self.send_single_request(request, timeout)
>   File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpx\_client.py", line 714, in send_single_request
>     ) = transport.request(
>   File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpcore\_sync\connection_pool.py", line 152, in request
>     response = connection.request(
>   File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpcore\_sync\connection.py", line 65, in request
>     self.socket = self._open_socket(timeout)
>   File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpcore\_sync\connection.py", line 85, in _open_socket
>     return self.backend.open_tcp_stream(
>   File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpcore\_backends\sync.py", line 139, in open_tcp_stream
>     return SyncSocketStream(sock=sock)
>   File "C:\Users\LENOVO\.conda\envs\USA24\lib\contextlib.py", line 131, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "C:\Users\LENOVO\.conda\envs\USA24\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
>     raise to_exc(exc) from None
> httpcore._exceptions.ConnectTimeout: _ssl.c:1106: The handshake operation timed out
> ```
> 
plz check your internet connection

**Comment by IslandScientistKojima** [comment]
> @gelodefaultbrain是的，請求的上限是2000次左右，我用60s延時函數處理。效果還不錯，已經連續跑了一天了。

You mean "time.sleep(60)" ?
