### ISSUE TITLE
ImportError: cannot import name 'Timeout'

### ISSUE THREAD

**Issue by mirfan899** [ssut/py-googletrans#262]
**Googletrans version:**
- [ x] **3.x**
- [ ] **2.x**

**I'm submitting a ...** 

- [x ] bug report
- [ ] feature request

**Current behavior:**
Tried to use it in Python 3.6 and throws some strange error of `timeout`

**Steps to reproduce:**
Install on Ubuntu 18.04, Python 3.6. Import it and throws an error.

**Related code:**

```python
import googletrans
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/irfan/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/202.7660.27/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/irfan/environments/SquadTranslationUrdu/lib/python3.6/site-packages/googletrans/__init__.py", line 6, in <module>
    from googletrans.client import Translator
  File "/home/irfan/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/202.7660.27/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/irfan/environments/SquadTranslationUrdu/lib/python3.6/site-packages/googletrans/client.py", line 12, in <module>
    from httpx import Timeout
ImportError: cannot import name 'Timeout'
```

**Comment by mirfan899** [comment]
After digging into the issue, found out if the environment is not in the project directory it will throw an error like this. Creating an environment in the project directory fixed the issue, strangely got into another issue.

Here is what it shows when try to translate.
![pytranslate](https://user-images.githubusercontent.com/3822565/102080776-d6524400-3e30-11eb-9ec4-7d026860df3b.png)

**Comment by mirfan899** [comment]
Found a solution in another issue.
https://github.com/ssut/py-googletrans/issues/234#issuecomment-741942384
