### ISSUE TITLE
'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by watzon** [ssut/py-googletrans#265]
**Googletrans version:**
- [x] **3.x**
- [ ] **2.x**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**
Attempting to run the following basic example, I get the trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chriswatson/.local/share/virtualenvs/hikoki-gJ18aQp_/lib/python3.8/site-packages/googletrans/client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "/Users/chriswatson/.local/share/virtualenvs/hikoki-gJ18aQp_/lib/python3.8/site-packages/googletrans/client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "/Users/chriswatson/.local/share/virtualenvs/hikoki-gJ18aQp_/lib/python3.8/site-packages/googletrans/gtoken.py", line 194, in do
    self._update()
  File "/Users/chriswatson/.local/share/virtualenvs/hikoki-gJ18aQp_/lib/python3.8/site-packages/googletrans/gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
```

**Expected behavior:**
A translation should've been returned

**Steps to reproduce:**
Using Python 3.8.6 run the following example.

**Related code:**
```python
from googletrans import Translator
translator = Translator()
translator.translate("Hola muchacho")
```

**Comment by opennota** [comment]
Duplicate of https://github.com/ssut/py-googletrans/issues/234

**Comment by rickavmaniac** [comment]
Same as #234

**Comment by Alex0xf** [comment]
same to me

**Comment by KameniAlexNea** [comment]
same to me

**Comment by feihongloveworld** [comment]
same to me

**Comment by j1nma** [comment]
same

**Comment by pmi123** [comment]
Same for me. Tried to translate "Ich bin froh" (German) into English. The code was working up to the end of last year, then started getting the same error message `'NoneType' object has no attribute 'group'.`

```
[2021-02-03 22:32:03] DEBUG [translation_services.translation_services.google_service_1:97] text=Ich bin froh, dest_lang=en, src_lang=auto
[2021-02-03 22:32:03] DEBUG [urllib3.connectionpool._new_conn:815] Starting new HTTPS connection (1): translate.google.com:443
[2021-02-03 22:32:04] DEBUG [urllib3.connectionpool._make_request:396] https://translate.google.com:443 "GET / HTTP/1.1" 200 None
[2021-02-03 22:32:04] ERROR [translation_services.translation_services.google_service_1:111] Google translator failed. Retry count = 0.
Traceback (most recent call last):
  File "/home/mark/python-projects/archive/translation_services/translation_services.py", line 105, in google_service_1
    translation_obj = translator.translate(text, dest=dest_lang)
  File "/home/mark/.virtualenvs/archive/lib/python3.6/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/mark/.virtualenvs/archive/lib/python3.6/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/mark/.virtualenvs/archive/lib/python3.6/site-packages/googletrans/gtoken.py", line 200, in do
    self._update()
  File "/home/mark/.virtualenvs/archive/lib/python3.6/site-packages/googletrans/gtoken.py", line 65, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by ArtanisTheOne** [comment]
Same ...

**Comment by terryyz** [comment]
For anyone receives `NoneType' object has no attribute 'group`, if you are currently using `googletrans==3.0.0`, please switch to `googletrans==3.1.0a0` for the temporary fix.
