### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by Nat1anWasTaken** [ssut/py-googletrans#299]
**Googletrans version:**
- [ ] **4.0.0rc1**
- [ ] **3.1.0a0**
- [x] **3.0.0**
- [ ] **2.x**

**I'm submitting a...** 

- [x] bug report
- [ ] feature request

**Current behavior:**

It throws `AttributeError: 'NoneType' object has no attribute 'group'` error.

**Expected behavior:**

Print the translated text of "我覺得今天天氣不好"
**Related code:**

There is the full error
```py
Traceback (most recent call last):
  File "C:\Users\hong\Desktop\VS_codes\line_bot\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\hong\Desktop\VS_codes\line_bot\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\hong\Desktop\VS_codes\line_bot\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\hong\Desktop\VS_codes\line_bot\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:/Users/hong/Desktop/VS_codes/line_bot/app.py", line 126, in callback
    handler.handle(body, signature)
  File "C:\Users\hong\Desktop\VS_codes\line_bot\venv\lib\site-packages\linebot\webhook.py", line 260, in handle
    self.__invoke_func(func, event, payload)
  File "C:\Users\hong\Desktop\VS_codes\line_bot\venv\lib\site-packages\linebot\webhook.py", line 272, in __invoke_func
    func(event)
  File "C:/Users/hong/Desktop/VS_codes/line_bot/app.py", line 198, in handle_message
    print('English:', translator.translate('我覺得今天天氣不好', dest='en').text)
  File "C:\Users\hong\Desktop\VS_codes\line_bot\venv\lib\site-packages\googletrans\client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "C:\Users\hong\Desktop\VS_codes\line_bot\venv\lib\site-packages\googletrans\client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "C:\Users\hong\Desktop\VS_codes\line_bot\venv\lib\site-packages\googletrans\gtoken.py", line 194, in do
    self._update()
  File "C:\Users\hong\Desktop\VS_codes\line_bot\venv\lib\site-packages\googletrans\gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
```
And my code
```py
translator = googletrans.Translator()
print(translator.translate('我覺得今天天氣不好', dest='en').text)
```

**Comment by BlackFishY** [comment]
same question to me

**Comment by Tizioincognit0** [comment]
I've the same issue.

**Comment by ProgrammingPlanet** [comment]
same here

**Comment by nowfalsalahudeen** [comment]
use 3.1.0a0 version.

**Comment by Tizioincognit0** [comment]
> use 3.1.0a0 version.

But also that version has an issue: https://github.com/ssut/py-googletrans/issues/300.

**Comment by mantelllo** [comment]
Same error with 3.1.0a0.

**Comment by jan-kwiatkowski** [comment]
got same problem

**Comment by Schmarotzer** [comment]
got same problem
`Traceback (most recent call last):
  File "c:/Users/Schmarotzer/Documents/Python/exp2.py", line 3, in <module>
    translator.translate('안녕하세요.', dest='en')
  File "C:\Users\Schmarotzer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "C:\Users\Schmarotzer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "C:\Users\Schmarotzer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\gtoken.py", line 194, in do
    self._update()
  File "C:\Users\Schmarotzer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by braindevices** [comment]
this hit me too

**Comment by fcolecumberri** [comment]
+1

**Comment by oleksandrsirenko** [comment]
Unfortunately, the library doesn't work at all (

**Comment by Riyas3** [comment]
Facing the same issue

**Comment by gabrielcassimiro17** [comment]
I'm having the same problem

**Comment by aPToul** [comment]
Same.

**Comment by qinghuan1998** [comment]
use googletrans==4.0.0rc1 version can solve your problem. Although the latest version installed by default is shown as 3.0.0, there is still version 4.0.0rc1.
使用4.0.0rc1版本可以解决这个问题，默认安装的最新版本为3.0.0，但是可以指定安装4.0.0rc1版本

**Comment by mohith7548** [comment]
`googletrans==4.0.0rc1` is also having the same issue. Any solution?
```python3
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by NawtJ0sh** [comment]
https://github.com/ssut/py-googletrans/issues/268

**Comment by Tizioincognit0** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

Anyway it hasn't been fixed yet.

**Comment by Tizioincognit0** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

Anyway it hasn't been fixed yet.

**Comment by Tizioincognit0** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

Anyway it hasn't been fixed yet.

**Comment by ttmx** [comment]
Updates? Same issue here.

**Comment by Tizioincognit0** [comment]
It must be fixed!

**Comment by Tizioincognit0** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
> 
Anyway it hasn't been fixed yet.

**Comment by chenxs1427** [comment]
same problems, there is something wrong with the file **gtoken.py**, i think may be google translate website had updated their token system

**Comment by salama4ai** [comment]
the same frustrating issue

**Comment by salama4ai** [comment]
installing ```googletrans==4.0.0rc1``` fix the issue for me at least

**Comment by Tizioincognit0** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
> Anyway it hasn't been fixed yet.

**Comment by salama4ai** [comment]
@Tizioincognit0  i could solve the issue by installing different version, kindly try that

**Comment by Tizioincognit0** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
> 

Anyway it hasn't been fixed yet.

**Comment by JohnMcC1** [comment]
I am using version 4, get same error after 32nd  string is sent. python3.10  Even requestng slowly.  Responds with problem with client.py, translated parts, line 194
TypeError: 'NoneType' object is not iterable

**Comment by Tizioincognit0** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
> 

Anyway it hasn't been fixed yet.

**Comment by noah-art3mis** [comment]
+1
