### ISSUE TITLE
Encoding error with python2

### ISSUE THREAD

**Issue by orionCMCMSU** [ssut/py-googletrans#3]
```
$ translate -d ru "test"
Traceback (most recent call last):
  File "/usr/local/bin/translate", line 44, in <module>
    main()
  File "/usr/local/bin/translate", line 40, in main
    pronunciation=pronunciation)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
```

works well with python3

**Comment by ssut** [comment]
Hello, I fixed an error where the UnicodeEncodeError occurred in Python 2.x, please check it again with master branch of py-googletrans.
Regardless of whether or not this is fixed, please let me know.
