### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by Sengolda** [ssut/py-googletrans#304]
# I'm using v3 of googletrans.
 - code:
 ```py
from googletrans import Translator
translator = Translator()
translator.translate('안녕하세요.')
translator.translate('안녕하세요.', dest='ja')
translator.translate('veritas lux mea', src='la')
```

The error is
```
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/jishaku/features/python.py", line 95, in jsk_python
    async for send, result in AsyncSender(executor):
  File "/home/container/.local/lib/python3.8/site-packages/jishaku/functools.py", line 109, in _internal
    value = await base.asend(self.send_value)
  File "/home/container/.local/lib/python3.8/site-packages/jishaku/repl/compilation.py", line 140, in traverse
    async for send, result in AsyncSender(func(*self.args)):
  File "/home/container/.local/lib/python3.8/site-packages/jishaku/functools.py", line 109, in _internal
    value = await base.asend(self.send_value)
  File "<repl>", line 7, in _repl_coroutine
    translator.translate('안녕하세요.')
  File "/home/container/.local/lib/python3.8/site-packages/googletrans/client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "/home/container/.local/lib/python3.8/site-packages/googletrans/client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "/home/container/.local/lib/python3.8/site-packages/googletrans/gtoken.py", line 194, in do
    self._update()
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by huochequan** [comment]
googletrans-4.0.0rc1-py3.9.egg-info

try this version

**Comment by NawtJ0sh** [comment]
https://github.com/ssut/py-googletrans/issues/268

**Comment by ratikumari227** [comment]
I am also facing a similar issue with error as:

AttributeError                            Traceback (most recent call last)
<ipython-input-19-dae44678dff2> in <module>()
      4 from googletrans import Translator
      5 translator = Translator()
----> 6 translator.translate('안녕하세요.')

3 frames
/usr/local/lib/python3.7/dist-packages/googletrans/gtoken.py in _update(self)
     60 
     61         # this will be the same as python code after stripping out a reserved word 'var'
---> 62         code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
     63         # unescape special ascii characters such like a \x3d(=)
     64         code = code.encode().decode('unicode-escape')

AttributeError: 'NoneType' object has no attribute 'group'

**Comment by eungangku** [comment]
> try this version by pip install 'googletrans==4.0.0rc1' or pip install 'googletrans==3.1.0a0'

First one works very well
