### ISSUE TITLE
File "/usr/local/lib/python3.6/site-packages/googletrans/gtoken.py", line 62, in _update

### ISSUE THREAD

**Issue by x011** [ssut/py-googletrans#313]
Tested with googletrans-3.0.0 using python3.6 on Linux and Windows:

```
Traceback (most recent call last):
  File "translate_strings.py", line 11, in <module>
    x = translator.translate('Ol\xe1', dest='en')
  File "/usr/local/lib/python3.6/site-packages/googletrans/client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "/usr/local/lib/python3.6/site-packages/googletrans/client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "/usr/local/lib/python3.6/site-packages/googletrans/gtoken.py", line 194, in do
    self._update()
  File "/usr/local/lib/python3.6/site-packages/googletrans/gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
```
Any idea how to solve this?

**Comment by FeraruSilviuMarian** [comment]
got the same error, it used to work before, now it doesn't all of the sudden

**Comment by opelkus** [comment]
Same error

**Comment by miguel-mira** [comment]
I have the same error!! It was working last week. What versions are you using? I have googletrans==4.0.0rc1

**Comment by arainboldt** [comment]
looks like the google's blocked the handshake.

**Comment by msr8** [comment]
https://github.com/ssut/py-googletrans/issues/280
