### ISSUE TITLE
'Translator' object has no attribute 'raise_Exception'

### ISSUE THREAD

**Issue by mrgamer45** [ssut/py-googletrans#316]
**Googletrans version:**
- [x] **4.0.0rc1**
- [ ] **3.1.0a0**
- [ ] **3.0.0**
- [ ] **2.x**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**

Random error
**Expected behavior:**

It would be able to translate
**Steps to reproduce:**

Idk translate a bunch of stuff
**Related code:**

Error:
```
Traceback (most recent call last):
  File "C:\Users\Tristan Murphy\Documents\MC Resource Packs\translator.py", line 20, in <module>
    translated = translator.translate(str(content[key]), dest='zh-TW')
  File "C:\Users\Tristan Murphy\.conda\envs\main_venv\lib\site-packages\googletrans\client.py", line 194, in translate
    data, response = self._translate(text, dest, src)
  File "C:\Users\Tristan Murphy\.conda\envs\main_venv\lib\site-packages\googletrans\client.py", line 122, in _translate
    if r.status_code != 200 and self.raise_Exception:
AttributeError: 'Translator' object has no attribute 'raise_Exception'
```

**Other information:**

**Comment by MrBuzzy4** [comment]
I have that pronlem too, when start translate.

**Comment by great-analyzer** [comment]
Got 1000 lines to translate, got stopped at different locations...

Traceback (most recent call last):
  File "c:/Git/SRT Util/extract 2 translate.py", line 32, in <module>
    tranlated = translator.translate(text=first, dest='ja', src='ja')
  File "C:\Users\felix\AppData\Local\Programs\Python\Python38-32\lib\site-packages\googletrans\client.py", line 194, in translate
    data, response = self._translate(text, dest, src)
  File "C:\Users\felix\AppData\Local\Programs\Python\Python38-32\lib\site-packages\googletrans\client.py", line 122, in _translate
    if r.status_code != 200 and self.raise_Exception:
AttributeError: 'Translator' object has no attribute 'raise_Exception'
PS C:\Git>

**Comment by Bugbighuang** [comment]
Speed limits may be required

time.sleep(random.random()+1)

**Comment by HyperCodec** [comment]
I believe I fixed this a while ago (don't really remember, I either have given up or completed the project and moved on). The solution was probably ratelimit, fixable by using `time.sleep(8)` or something of the sort.

**Comment by jenny5587** [comment]
Should I put the speed limit in the for statement?
