### ISSUE TITLE
googletrans is not working 

### ISSUE THREAD

**Issue by Lokeshthakur1** [ssut/py-googletrans#346]
python code

from googletrans import Translator
translator = Translator()
translated = translator.translate('svízelná situace', src='cs', dest='hu')
print(translated.text)

this error

D:\work\python\google-message>py index.py
Traceback (most recent call last):
  File "index.py", line 48, in <module>
    translated = translator.translate('svízelná situace', src='cs', dest='hu')
  File "C:\Users\lthak\AppData\Roaming\Python\Python37\site-packages\googletrans\client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "C:\Users\lthak\AppData\Roaming\Python\Python37\site-packages\googletrans\client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "C:\Users\lthak\AppData\Roaming\Python\Python37\site-packages\googletrans\gtoken.py", line 194, in do
    self._update()
  File "C:\Users\lthak\AppData\Roaming\Python\Python37\site-packages\googletrans\gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by fullbright** [comment]
Same issue here. Did you find a solution?

**Comment by fullbright** [comment]
Duplicate with #234

**Comment by amirbtb** [comment]
Same error.

**Comment by recalldude** [comment]
same !

**Comment by kurtabela** [comment]
Same issue, doing `pip install googletrans==4.0.0rc1` worked for me

**Comment by raz0229** [comment]
```self.RE_TKK.search(r.text)``` in ```gtoken.py``` returns a None. Can't understand the regex pattern unfortunately

**Comment by ehsong** [comment]
> install googletrans==4.0.0rc1

So this doesn't throw the group error, but says `<googletrans.models.Translated at 0x7fa291190820>`, doesn't show the translation?
