### ISSUE TITLE
AttributeError: 'Translator' object has no attribute 'raise_Exception'

### ISSUE THREAD

**Issue by xLinkOut** [ssut/py-googletrans#350]
**Googletrans version:**
- [x] **4.0.0rc1**
- [ ] **3.1.0a0**
- [ ] **3.0.0**
- [ ] **2.x**

**I'm submitting a ...** 
- [x] bug report
- [ ] feature request

**Current behavior:**
During a translation, if the 'status code' obtained is not 200, the 'AttributeError' exception is thrown as 'self.raise_Exception' is not found.

**Expected behavior:**
Maybe retrying with another service url, and continue to translate.

**Steps to reproduce:**
It happen while performing translation in a loop, after a bunch of request it may receive a non-200 response code.

**Related code:**
File: `googletrans/client.py`:
```python
r = self.client.post(url, params=params, data=data)

if r.status_code != 200 and self.raise_Exception:  # Here, change 'Exception' to 'exception'
    raise Exception('Unexpected status code "{}" from {}'.format(
        r.status_code, self.service_urls))

return r.text, r
```

**Other information:**
```bash
Traceback (most recent call last):
  File "translate.py", line 95, in <module>
    output[lang][page_name][key] = translator.translate(value, src='en', dest=lang).text
  File "[redacted]/venv/lib/python3.8/site-packages/googletrans/client.py", line 194, in translate
    data, response = self._translate(text, dest, src)
  File "[redacted]/venv/lib/python3.8/site-packages/googletrans/client.py", line 122, in _translate
    if r.status_code != 200 and self.raise_Exception:
AttributeError: 'Translator' object has no attribute 'raise_Exception'
```

**Comment by JettScythe** [comment]
How are you calling it? I found a workaround to be `Translator(raise_exception=True)`

**Comment by djacu** [comment]
I'm getting the same error and I don't think using `Translator(raise_exception=True)` is the right fix.

My error is as follows:

```shell
Traceback (most recent call last):
  File "[HOME]/dev/python/translate-gte2-quests/convert_quests.py", line 63, in <module>
    main()
  File "[HOME]/dev/python/translate-gte2-quests/convert_quests.py", line 56, in main
    update_quest_file(quest_file=quest_file)
  File "[HOME]/dev/python/translate-gte2-quests/convert_quests.py", line 50, in update_quest_file
    fin.write(update_quest(raw_text))
  File "[HOME]/dev/python/translate-gte2-quests/convert_quests.py", line 36, in update_quest
    quest = quest.replace(title, translate_line(title))
  File "[HOME]/dev/python/translate-gte2-quests/convert_quests.py", line 20, in translate_line
    return translator.translate(line, src='ja', dest='en').text
  File "[HOME]/anaconda3/envs/google-trans/lib/python3.10/site-packages/googletrans/client.py", line 194, in translate
    data, response = self._translate(text, dest, src)
  File "[HOME]/anaconda3/envs/google-trans/lib/python3.10/site-packages/googletrans/client.py", line 122, in _translate
    if r.status_code != 200 and self.raise_Exception:
AttributeError: 'Translator' object has no attribute 'raise_Exception'. Did you mean: 'raise_exception'?
```

Looking at the code in `client.py` at lines 121-123 I see:

```python
         if r.status_code != 200 and self.raise_Exception:                                                                                                 
             raise Exception('Unexpected status code "{}" from {}'.format(                                                                                 
                 r.status_code, self.service_urls)) 
```

The `Translator` class has no `raise_Exception` attribute but it does have `raise_exception`. I believe `self.raise_Exception` needs to be changed to `self.raise_exception` on line 122.

I'm happy to submit a PR but I don't see a `4.0.0rc1` branch. @ssut is there a way to submit a PR to `4.0.0rc1`?

**Comment by djacu** [comment]
I just saw https://github.com/ssut/py-googletrans/issues/178
@terryyz are you the right person to contact?
