### ISSUE TITLE
Question: Is 3.1.0a0 released?

### ISSUE THREAD

**Issue by uncomfyhalomacro** [ssut/py-googletrans#362]
tried to package this for openSUSE, but it seems 3.1.0a0 does not have a pre-release tarball?

```shell
> py2pack fetch googletrans 3.1.0a0
Traceback (most recent call last):
  File "/usr/bin/py2pack", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/py2pack/__init__.py", line 366, in main
    args.func(args)
  File "/usr/lib/python3.10/site-packages/py2pack/__init__.py", line 94, in fetch
    fetch_data(args)
  File "/usr/lib/python3.10/site-packages/py2pack/__init__.py", line 275, in fetch_data
    releases = args.fetched_data['releases']
KeyError: 'releases'
```

**Comment by uncomfyhalomacro** [comment]
Closing. It seems to be that py2pack only uses versions that are stable releases
