### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by BaseMax** [ssut/py-googletrans#366]
Source code:
```
from googletrans import Translator

# translator = Translator(service_urls=[
# 	'translate.google.com',
# ])
translator = Translator()

data = str(open('first-post.md', encoding='utf8', newline='\n').read())
# print(data)
translations = translator.translate([data], src='en', dest='fa')
print(translations)
print(translations._response.http_version)

for translation in translations:
	print(translation.origin, ' -> ', translation.text)
```

Output:
```
C:\Users\Max\Desktop>python translate.py
Traceback (most recent call last):
  File "C:\Users\Max\Desktop\translate.py", line 10, in <module>
    translations = translator.translate([data], src='en', dest='fa')
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\googletrans\client.py", line 177, in translate
    translated = self.translate(item, dest=dest, src=src, **kwargs)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\googletrans\client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\googletrans\client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\googletrans\gtoken.py", line 194, in do
    self._update()
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\googletrans\gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
```

More information:
```
C:\Users\Max\Desktop>python --version
Python 3.10.8
```

Content of __init__.py file:
```
"""Free Google Translate API for Python. Translates totally free of charge."""
__all__ = 'Translator',
__version__ = '3.0.0'


from googletrans.client import Translator
from googletrans.constants import LANGCODES, LANGUAGES  # noqa
```

**Comment by l0rtk** [comment]
Probably [helpful](https://github.com/ssut/py-googletrans/issues/260)

**Comment by Charles-ux-bit** [comment]
Got the same problem

**Comment by excelant100** [comment]
Also got the same problem...

**Comment by Kasherpete** [comment]
I currently have this problem as well

**Comment by Kasherpete** [comment]
Actually, I just got it to fix by updating to the newest version. That will solve the problem

**Comment by BaseMax** [comment]
> Actually, I just got it to fix by updating to the newest version. That will solve the problem

Oh nice, How and to which version?

**Comment by l0rtk** [comment]
> > Actually, I just got it to fix by updating to the newest version. That will solve the problem
> 
> Oh nice, How and to which version?

4.0.0-rc1 this version works

**Comment by decibel1030** [comment]
> > Actually, I just got it to fix by updating to the newest version. That will solve the problem
> 
> Oh nice, How and to which version?

pip install googletrans==4.0.0-rc1

**Comment by bigplayer-ai** [comment]
the same problem here.

**Comment by alphaoumardev** [comment]
The same problem here too

**Comment by Kasherpete** [comment]
I remember that I was able to fix this issue, but I cannot remember exactly how. However It seems that it works on version 4.0.0-rc1, so instead of doing pip install try to force it to do the most recent version. Seems backwards but I believe that is how I fixed it, all I remember was that it was an easier fix than I thought.

**Comment by Kasherpete** [comment]
Try pip install googletrans==4.0.0-rc1

**Comment by Yildirimm** [comment]
However, [this](https://stackoverflow.com/questions/52455774/googletrans-stopped-working-with-error-nonetype-object-has-no-attribute-group) link worked for me.
It uses an older version of googletrans
`pip install googletrans==3.1.0a0`

**Comment by alphaoumardev** [comment]
It works for me

**Comment by Kasherpete** [comment]
Weird, do you have a sample code @Yildirimm?

**Comment by TheFaheem** [comment]
> However, [this](https://stackoverflow.com/questions/52455774/googletrans-stopped-working-with-error-nonetype-object-has-no-attribute-group) link worked for me. It uses an older version of googletrans `pip install googletrans==3.1.0a0`

Excellent This Worked for me!

**Comment by cgaravitoc** [comment]
there is a way to install last version with conda? I mean, which will be the solution to avoid conflicts for an env fully created with conda?

**Comment by ErtungaYusuf** [comment]
For those who have the same problem. Just make sure don't forget to install the working versions (4.0.0-rc1 or 3.1.0a0) in the venv, like me. it took me 1 hour to figure out where I went wrong.

**Comment by Madhav555-has** [comment]
i am having the same issue. i have tried both version 4.0.0-rc1 and 3.1.0a0. both of them gives error none type has no attribute group. the code was working find in my local host. but in client server it does not work. what is the issue. i am using 3.1.0a0 as of now

**Comment by sarc0m3** [comment]
Version 4.0.0-rc1 did the trick for me

**Comment by BHznJNs** [comment]
> However, [this](https://stackoverflow.com/questions/52455774/googletrans-stopped-working-with-error-nonetype-object-has-no-attribute-group) link worked for me. It uses an older version of googletrans `pip install googletrans==3.1.0a0`

Thank you, it works!

**Comment by ssut** [comment]
I have officially released [version 4.0.0 of py-googletrans](https://pypi.org/project/googletrans/). I will now close issues related to earlier versions. If you are still experiencing the same issue in the latest release, please open a new issue. I apologize for the delay in addressing these issues and hope the latest release resolves them. Thank you for your understanding.
