### ISSUE TITLE
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

### ISSUE THREAD

**Issue by lixnvege** [ssut/py-googletrans#379]
**Googletrans version:**
- [x] **4.0.0rc1**
- [ ] **3.1.0a0**
- [ ] **3.0.0**
- [ ] **2.x**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**

I met this error when I want to get the text of translated result:
Traceback (most recent call last):
  File "/dss/dsshome1/0F/di93box/summarization/probe.py", line 9, in <module>
    text_en = translator.translate(
  File "/dss/dsshome1/0F/di93box/tmp_pyenv/lib/python3.8/site-packages/googletrans/client.py", line 219, in translate
    parsed = json.loads(data[0][2])
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

The text length of the original text is 1338, not longer than 5k or 1500 which I have seen in some issues.
**Expected behavior:**

**Steps to reproduce:**

**Related code:**
one example:
from googletrans import Translator

translator = Translator()

origin_text = 'የ28 አመቷ ሴት ስሟ እንዲገለጥ ያልተፈለገ ሲሆን ንቦቹ አይኗ ውሰጥ ሲገቡ እርሷ አረም እያረመች ነበር ተብሏል። ዶ/ር ሆንግ ቺ ቲንግ ከታማሚዋ አይን ውስት አራት ሚሊ ሜትር ርዝመት ያላቸው ሃሊሲቲዴት ተብለው የሚጠሩት ወይም ማንኛውንም እርጥበት ስለሚወዱ በተለምዲ ላብ ቀሳሚ የሚል ስያሜ ያላቸው ንቦችን ጎትተው ሲያወጡ ክው ብለው ደንግጠው ነበር። ታማሚዋ አሁን ከሆስፒታል የወጣች ሲሆን በቤቷ ሆና እያገገመች ነው ተብሏል። ስዊት ቢ (ላብ ቀሳሚ) የሚባሉት የንብ ዝርያዎች በማንኛውም እርጥበት የሚሳቡ ሲሆን ላብና እንባን ለመቅሰም ሲሉ ወደ ሰዎች ይመጣሉ። ያለባቸውን ከፍተኛ የሆነ የፕሮቲን ፍላጎት ለማሟላትም እንባ ቀለባቸው ነው ሲሉ ይናገራሉ ባለሙያዎች። • "ኢትዮጵያ የከሸፈች ሀገር እየሆነች ነው" ሻለቃ ዳዊት • የኢቲ 302 የመጨረሻዎቹ ስድስት ደቂቃዎች • ከ28 ዓመታት በኋላ ዳግም ለዕይታ የበቃው ተውኔት ታማሚዋ እነዚህ ንቦች የግራ አይኗ ውስጥ ተወርውረው ጥልቅ ሲሉ እርሷ የዘመዶቿ መቃብር ዙሪያ የበቀለ አረምን ትነቃቅል ነበር። የዘመዶቿን መቃብር ለመጎብኘት የሄደችው ደግሞ በሀገሩ ባህልና ወግ መሰረት አመታዊ ልምዷን ለማድረስ ነበር። ንፋስ ነፍሶ አይኗ ውስጥ አንዳች ነገር ሲገባ ገምታ የነበረው ቆሻሻ እንደገባባት ነበር። ከሰአታት በኋላ ግን አይኗ እንዳበጠ ሲሆን ህመሙም እየጠነከረ መጣ። ያኔ ነው ሐኪም ወዳለበት ያመራችው። ሆስፒታል ደርሳ ያዩትን ለቢቢሲ ያስረዱት ሐኪም "አይኖቿን ሙሉ በሙሉ አልጨፈነችውም ነበር። በነበረው ክፍተት በአጉሊ መነፅር ስመለከት የነፍሳት እግር የሚመስል ጥቁር ነገር አየሁ። " ይላሉ። "ከዚያም አንዱን ይዤ ቀስ ብዬ አወጣሁት። ከዛ ሌላ፣ ደግሞ ሌላ፣ እንደገና ሌላ። ሁሉም በሕይወት ነበሩ። " ዶክተሩ አክለውም ንቦቹ ሊሞቱ ይችሉ ነበር። ንፋሱ ያመጣው አቧራ ላይ ተጣብቀው እንዲቆዩ አድርጓቸው ነው ብለዋል። "እነዚህ ንቦች ሰው አይተናኮሉም ነገር ግን ላብ ይጠጣሉ። ስማቸውም ከዚያ የመጣ ነው" ሲሉ ያብራራሉ። ታማሚዋ ንቦቹ አይኖቿ ውስጥ እንደገቡ አይኗን አለማሸቷ እንደረዳት ያሰመሩበት ዶክተሩ "ኮንታክት ሌንስ ስላደረገች ለማሸት አልፈለገችም። ምክንያቱም ሌንሱ ይሰበራል ብላ ሰግታለች። ያንን አለማድረጓ ደግሞ ንቦቹ መርዛቸውን እንዳይረጩ አድርጓል። ያ ሆኖ ቢሆን ኖሮ ትሞት ነበር" ብለዋል። ንቦቹ አሁንም በሕይወት ያሉ ሲሆን ለምርምር ወደ ቤተ ሙከራ ተልከዋል።'

text_en = translator.translate(
                origin_text,
                dest='en',
                src='am')
print(text_en.text)

```
insert short code snippets here
```

**Other information:**

**Comment by withAI888** [comment]
I also encountered this problem, did you solve it?

**Comment by lionderful** [comment]
I also encountered this problem, did you solve it?

**Comment by lionderful** [comment]
> I also encountered this problem, did you solve it?

pip install googletrans==3.1.0a0
