### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by tramstheman** [ssut/py-googletrans#38]
**Background**
I am translating reviews, some of which have emojis in them. This one review in particular has been breaking while attempting to translate. After debugging, I found that it was this emoji in particular that seems to be breaking the translation where as other emojis _appear_ to be working fine. The google api should be able to handle emojis. 

**Issue**
The following command will break break translations: 

`text = Translator().translate('😩').text`

**Stack Trace**
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/googletrans/client.py", line 132, in translate
    data = self._translate(text, dest, src)
  File "/Library/Python/2.7/site-packages/googletrans/client.py", line 63, in _translate
    data = utils.format_json(r.text)
  File "/Library/Python/2.7/site-packages/googletrans/utils.py", line 51, in format_json
    converted = json.loads(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by yftah89** [comment]
Hi, 
I'm getting the same error, how can I avoid it?

**Comment by Andy671** [comment]
Same here. Any ideas?
