### ISSUE TITLE
Tkk token not found

### ISSUE THREAD

**Issue by choppeh** [ssut/py-googletrans#429]
**Googletrans version:**
- [ ] **4.0.0rc1**
- [ ] **3.1.0a0**
- [x] **3.0.0**
- [ ] **2.x**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**

```bash
>>> from googletrans import Translator
>>> translator = Translator()
>>> translator.translate('안녕하세요.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/danroxha/Workspace/translate/lib64/python3.11/site-packages/googletrans/client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danroxha/Workspace/translate/lib64/python3.11/site-packages/googletrans/client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danroxha/Workspace/translate/lib64/python3.11/site-packages/googletrans/gtoken.py", line 194, in do
    self._update()
  File "/home/danroxha/Workspace/translate/lib64/python3.11/site-packages/googletrans/gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

```

**Expected behavior:**

Working README example

**Steps to reproduce:**

- Create a venv with python3.11;
- Install package with: ```pip install googletrans```;
- Open python REPL;
- Follow the README sample

**Related code:**

```py
from googletrans import Translator

translator = Translator()
translator.translate('안녕하세요.')
```

**Other information:**

**Comment by asskGit** [comment]
any solutions?

**Comment by ssut** [comment]
I have officially released [version 4.0.0 of py-googletrans](https://pypi.org/project/googletrans/). I will now close issues related to earlier versions. If you are still experiencing the same issue in the latest release, please open a new issue. I apologize for the delay in addressing these issues and hope the latest release resolves them. Thank you for your understanding.
