### ISSUE TITLE
Failure to decode unicode

### ISSUE THREAD

**Issue by TaylorWebb** [ssut/py-googletrans#49]
Trying to translate over certain unicode characters does not work. In particular, trying to translate with sentences that contain unicode characters that are emojis.

Traceback (most recent call last):
  File "C:/Users/Taylor/Desktop/TEST/sentAnalysis.py", line 139, in <module>
    main()
  File "C:/Users/Taylor/Desktop/TEST/sentAnalysis.py", line 95, in main
    translatedTweet = translator.translate(originalTweet, dest="en", src=tweetObject["lang"]).text
  File "C:\python36\lib\site-packages\googletrans\client.py", line 132, in translate
    data = self._translate(text, dest, src)
  File "C:\python36\lib\site-packages\googletrans\client.py", line 63, in _translate
    data = utils.format_json(r.text)
  File "C:\python36\lib\site-packages\googletrans\utils.py", line 62, in format_json
    converted = legacy_format_json(original)
  File "C:\python36\lib\site-packages\googletrans\utils.py", line 54, in legacy_format_json
    converted = json.loads(text)
  File "C:\python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by cutelittleturtle** [comment]
maybe a emoji pattern problem. As far as I tested, this api cannot work with emoji pattern right now.

Just get rid of emoji maybe?

**Comment by J16N** [comment]
When will this problem be solved? 😅
I don't know but I think [https://github.com/terryyin/translate-python/issues/27](they) have solved the problem.
