### ISSUE TITLE
"Your client does not have permission to get URL ..."

### ISSUE THREAD

**Issue by rr-** [ssut/py-googletrans#6]
I was trying out various translators to test whether I can ditch using [mine](https://github.com/rr-/translator) and this project looks promising, but I get 403 error with it:

``` console
rr-@tornado:~$ virtualenv derp    
Using base prefix '/usr'
New python executable in /home/rr-/derp/bin/python
Installing setuptools, pip, wheel...done.

rr-@tornado:~$ source ./derp/bin/activate 
(derp) rr-@tornado:~$ pip install py-googletrans
Collecting py-googletrans
Collecting requests (from py-googletrans)
  Using cached requests-2.9.1-py2.py3-none-any.whl
Collecting future (from py-googletrans)
Installing collected packages: requests, future, py-googletrans
Successfully installed future-0.15.2 py-googletrans-1.2 requests-2.9.1

(derp) rr-@tornado:~$ ./derp/bin/translate 子牛  
original text:  <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/translate_a/single?client=t&amp;sl=auto&amp;tl=en&amp;hl=en&amp;dt=bd&amp;dt=rm&amp;dt=ss&amp;dt=t&amp;dt=at&amp;ie=UTF-8&amp;oe=UTF-8&amp;q=%E5%AD%90%E7%89%9B</code> from this server.  <ins>That’s all we know.</ins>
  =>  <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/translate_a/single?client=t&amp;sl=auto&amp;tl=en&amp;hl=en&amp;dt=bd&amp;dt=rm&amp;dt=ss&amp;dt=t&amp;dt=at&amp;ie=UTF-8&amp;oe=UTF-8&amp;q=%E5%AD%90%E7%89%9B</code> from this server.  <ins>That’s all we know.</ins>

Traceback (most recent call last):
  File "/home/rr-/derp/lib/python3.5/site-packages/googletrans/conversion.py", line 34, in format_json
    converted = json.loads(text)
  File "/usr/lib64/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "./derp/bin/translate", line 44, in <module>
    main()
  File "./derp/bin/translate", line 30, in main
    result = translator.translate(args.text, dest=args.dest, src=args.src)
  File "/home/rr-/derp/lib/python3.5/site-packages/googletrans/translator.py", line 100, in translate
    data = format_json(r.text)
  File "/home/rr-/derp/lib/python3.5/site-packages/googletrans/conversion.py", line 38, in format_json
    return converted
UnboundLocalError: local variable 'converted' referenced before assignment
```

Note that I have no problems with web access or with my script.

**Comment by jegue** [comment]
Same Here! using a France server!
<title>Error 403 (Forbidden)!!1</title>

File "/usr/local/lib/python2.7/dist-packages/googletrans/conversion.py", line 38, in format_json
    return converted
UnboundLocalError: local variable 'converted' referenced before assignment

**Comment by rr-** [comment]
@jegue FYI I ended up using https://github.com/soimort/translate-shell - it seems to be actively maintained.
