### ISSUE TITLE
Problems from using it in the Python shell

### ISSUE THREAD

**Issue by chanonlim** [ssut/py-googletrans#80]
Alright, so I used this module, it used to work fine but when I tried to do it today, I got this error (I'm using Python 3.7)
``
>>> t = googletrans.Translator()
>>> t.translate('สวัสดี', dest='en')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\gtoken.py", line 180, in do
    self._update()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'``
I've seen this reported before but I don't really know how to "change to localhost"

**Comment by Darkblader24** [comment]
See here: #78

**Comment by chanonlim** [comment]
where should i replace it?
