### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by markolofsen** [ssut/py-googletrans#86]
```
Exception in thread Thread-728:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mark/Documents/htdocs/nextjs_django/backend/__sys_utils/TEXTLIB/translator.py", line 84, in trans
    text_arr[index] = Translator(proxies=getProxy()).translate(text, dest=lang_to).text
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'


```

**Comment by keypey** [comment]
Same here.
```
Traceback (most recent call last):
  File "/home/bruno/W7/Programowanie/python/3/children/ZaTosiaste/newTabliczkaMnozenia/test_google_trans.py", line 10, in <module>
    translator.translate('what do you want')
  File "/home/bruno/.local/share/virtualenvs/children-ZL65Ldm6/lib/python3.5/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/bruno/.local/share/virtualenvs/children-ZL65Ldm6/lib/python3.5/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/bruno/.local/share/virtualenvs/children-ZL65Ldm6/lib/python3.5/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/bruno/.local/share/virtualenvs/children-ZL65Ldm6/lib/python3.5/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by AritzBi** [comment]
Same here...

**Comment by keypey** [comment]
Solution in description:
[](url)https://github.com/ssut/py-googletrans/issues/77

It worked for me.
kp.

**Comment by markolofsen** [comment]
Fixed library are here [https://pypi.org/project/py-translator/](https://pypi.org/project/py-translator/)
