### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Hexbugman213** [ssut/py-googletrans#90]
_The discord things are because this is in a Discord bot_
Whenever I try to use the API, it returns this error. It seems like something with the key. Not sure.
```Traceback (most recent call last):
  File "C:\Users\minec\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 220, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 596, in on_message
    dt = translator.detect(message.content).lang
  File "C:\Users\minec\AppData\Local\Programs\Python\Python36\lib\site-packages\googletrans-2.3.0-py3.6.egg\googletrans\client.py", line 249, in detect
    data = self._translate(text, dest='en', src='auto')
  File "C:\Users\minec\AppData\Local\Programs\Python\Python36\lib\site-packages\googletrans-2.3.0-py3.6.egg\googletrans\client.py", line 81, in _translate
    data = utils.format_json(r.text)
  File "C:\Users\minec\AppData\Local\Programs\Python\Python36\lib\site-packages\googletrans-2.3.0-py3.6.egg\googletrans\utils.py", line 62, in format_json
    converted = legacy_format_json(original)
  File "C:\Users\minec\AppData\Local\Programs\Python\Python36\lib\site-packages\googletrans-2.3.0-py3.6.egg\googletrans\utils.py", line 54, in legacy_format_json
    converted = json.loads(text)
  File "C:\Users\minec\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\minec\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\minec\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

**Comment by Hexbugman213** [comment]
It also sometimes returns the known nonetype raw token error, but I fixed that with the fork of the API

**Comment by tgi01054** [comment]
@Hexbugman213 
Hello.
Which fork did you use? 
Could you tell me in detail?

**Comment by marchezinixd** [comment]
@markolofsen Can you fix this on your lib?

**Comment by nafseerk** [comment]
does anyone have a fix for this?

**Comment by Ouelbani-Abdelmalek** [comment]
i am facing the same problem. did anyone fix it?

**Comment by HexCodeFFF** [comment]
I think it means google blocked you from using it but not sure

**Comment by Ouelbani-Abdelmalek** [comment]
@HexCodeFFF Thanks for answering. i hope they didn't
