### ISSUE TITLE
Failed to parse: <proxy>:<port>

### ISSUE THREAD

**Issue by Hexbugman213** [ssut/py-googletrans#92]
I recently tried moving my python app (a Discord bot) to Heroku, and I started getting this error.

If this doesn't have to do with googletrans I'd appreciate any link that can help me solve this. Google search results came up inconclusive. Thank you!
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/requests/adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "/app/.heroku/python/lib/python3.6/site-packages/requests/adapters.py", line 305, in get_connection
    proxy_url = parse_url(proxy)
  File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/util/url.py", line 199, in parse_url
    raise LocationParseError(url)
urllib3.exceptions.LocationParseError: Failed to parse: <proxy>:<port>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 704, in on_message
    dt = translator.detect(message.content)  # detect
  File "/app/.heroku/python/lib/python3.6/site-packages/googletrans/client.py", line 249, in detect
    data = self._translate(text, dest='en', src='auto')
  File "/app/.heroku/python/lib/python3.6/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/app/.heroku/python/lib/python3.6/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/app/.heroku/python/lib/python3.6/site-packages/googletrans/gtoken.py", line 57, in _update
    r = self.session.get(self.host)
  File "/app/.heroku/python/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/requests/adapters.py", line 414, in send
    raise InvalidURL(e, request=request)
requests.exceptions.InvalidURL: Failed to parse: <proxy>:<port>
```

**Comment by Hexbugman213** [comment]
I am an idiot. It was code I added that I forgot about. My apologies.
